### ISSUE TITLE
Support for Kibana 5.6.2

### ISSUE THREAD

**Issue by keeshqs** [dlumbrer/kbn_searchtables#10]
Hi,

we badly need this plugin on our Kibana dashboard and right now we are using version 5.6.2 and we cannot downgrade to 5.5.x. We'll truly appreciate if you could advise on usage and if there are plans of supporting 5.6.2 anytime soon.

Thanks in advance,
Keeshia

**Comment by dlumbrer** [comment]
Hi @keeshqs, follow these steps:

Delete KIBANA_HOME/optimize/bundles first.

Clone the repo intro the plugins/ folder

Edit package.json for version 5.6.2.

Launch Kibana
