### ISSUE TITLE
No search bar in 6.1.1.

### ISSUE THREAD

**Issue by nikhilno1** [dlumbrer/kbn_searchtables#14]
I am not able to see the search bar in 6.1.1. It is working like a normal data table. Is that expected? 
Thanks,
Nikhil

**Comment by dlumbrer** [comment]
It is a bug, I'm fixing it!, sorry!

**Comment by dlumbrer** [comment]
Hi @nikhilno1 , Just fixed!!! you have the new version in releases!

**Comment by nikhilno1** [comment]
Hi David,

It's still not working for me.
How can I check what's wrong?

-Thanks
Nikhil

**Comment by keeshqs** [comment]
Hi David,

Same case with me. I've tried to delete the ./kibana/optimize/bundles folder and restart Kibana as suggested but it's still not working after.
