### ISSUE TITLE
Kibana 6.1 - Not fully enable ?

### ISSUE THREAD

**Issue by Poil** [dlumbrer/kbn_searchtables#16]
Hi,

In Kibana 6.1.3, I can see the Searchtables icons on the visualize panel, but the link is "https://kibana.local/app/kibana#/visualize/new/configure?type=table" like the normal DataTable; is it normal ?

Also, if I select it, there is no search input, so I think I'm in the normal DataTable.

Best regards

**Comment by dlumbrer** [comment]
Hi @Poil 

Did you download the latest version of releases?

**Comment by Poil** [comment]
It's a fresh clone of 6-dev :)

**Comment by dlumbrer** [comment]
mmmm, do you see the link "Search" in top left corner of the table?

**Comment by Poil** [comment]
No :/

**Comment by dlumbrer** [comment]
I've tested the plugin from cloning and downloading from releases and it works for me in my Kibana 6.1.3

**Comment by dlumbrer** [comment]
Ok @Poil , my fault, just fixed the error, I'm really sorry


Try again and tell me if now you can see the link "Search"

**Comment by Poil** [comment]
It's working ! Many_ thanks ! :)
