### ISSUE TITLE
Use .tar.xz suffix for files compressed with xz

### ISSUE THREAD

**Issue by szymonk** [dlumbrer/kbn_searchtables#18]
Hello,

The [releases page](https://github.com/dlumbrer/kbn_searchtables/releases) contains a link to the [kbn_searchtables.tar.gz](https://github.com/dlumbrer/kbn_searchtables/releases/download/6.X-1/kbn_searchtables.tar.gz) file which is supposed to be a gz-compressed file but in fact it is compressed with xz. Please keep the suffix consistent with the actual compression method used (either rename the file or compress it with gz).

Best regards,
szymonk

**Comment by dlumbrer** [comment]
Done, thanks!
