### ISSUE TITLE
Search by regular expression instead of exact match

### ISSUE THREAD

**Issue by jsmanrique** [dlumbrer/kbn_searchtables#23]
It seems that the plugin searches for exact match text in the table fields, instead of fields that contain a text string as part of table fields content.

For example, if I search for "Manrique" in a table that I know it has a "J. Manrique Lopez de la Fuente" entry, I don't get any result. The only way to get those rows with that string is to search for that exact (long) string. Tested in [chaoss.biterg.io](https://chaoss.biterg.io)

Wouldn't it be great that searching for `text` resolves to all the rows with `.*text*` (or similar, I am not an expert in regular expressions) in their fields?

**Comment by dlumbrer** [comment]
Hi @jsmanrique, with the new feature added by a community member (#20) this bug is solved.

Now can search items that are numbers and also search as you are filling the search input.
