### ISSUE TITLE
Add [ENTER] touch support

### ISSUE THREAD

**Issue by fbaligand** [dlumbrer/kbn_searchtables#4]
This would be great that, when we touch [ENTER] key on search field, it launches search (like when we click on "Search" button).

**Comment by seoa** [comment]
I implemented this by adding a ng-keypress="doSearchEnter($event)" to the input tags in html, and adding the function to the controller which checks event.which === 13 and then does the same thing as doSearch().

**Comment by fbaligand** [comment]
Great !
Could you make a PR to provide the feature ?
