### ISSUE TITLE
this plugin work's fine on 5.5 but not on 5.6.1

### ISSUE THREAD

**Issue by TRISAF** [dlumbrer/kbn_searchtables#7]
Hi,
this plugin work's fine on 5.5 but not on 5.6.1
The error is:
Uncaught TypeError: Cannot read property 'get' of undefined (http://localhost:5601/bundles/kibana.bundle.js?v=15533:153)
Version: 5.6.1
Build: 15533
Error: Uncaught TypeError: Cannot read property 'get' of undefined (http://localhost:5601/bundles/kibana.bundle.js?v=15533:153)
    at window.onerror (http://localhost:5601/bundles/commons.bundle.js?v=15533:76:8876)

Any idea for fix this error?

Many thanks
Filippo

**Comment by dlumbrer** [comment]
Hi @TRISAF ,

I'm going to test the plugin in that version.

I'll keep this issue opened!!

Thx

**Comment by dlumbrer** [comment]
Hi @TRISAF,

I dont have problems using it on 5.6.1, did you change the kibana/version of package.json?

**Comment by TRISAF** [comment]
With a fresh installation of kibana and the plugin,  it works fine.
Many thanks for the attention
Filippo
